[package]
name = "cid"
version = "1.1.0"
description = "Motoko implementation of Content Identifiers (CIDs) for use with IPFS and IPLD."
repository = "https://github.com/edjcase/motoko_cid"
keywords = [
  "cid",
  "content",
  "identifier",
  "addressable",
  "ipfs",
  "multiformats",
  "multihash",
  "multicodec",
  "multibase",
  "ipld",
]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"
"multiformats@2" = "2.1.0"
"xtended-iter@1" = "1.1.0"
"buffer@0" = "0.1.0"
"base-x-encoder@2" = "2.1.0"

[dev-dependencies]
test = "2.1.1"
